export const USER_MESSAGES = {
    USER_NOT_FOUND: "User not found",
    INVALID_PASSWORD: "Invalid password",
    LOGIN_SUCCESS: "User logged in successfully",
    USER_CHECK_ERROR: "Failed to check user",
    ALL_FILD_REQUIRED:"All fields are required",
    FAILD_TO_CREATE_USER:"Failed to create user",
    CREATEUSER:"user created successfully",
    FAILD_TO_HASHPASSWORD:"Failed to hash password",
    KYC_CREATED:"Kyc created successfully",
    TOKEN_REQUIRED:"Token is required",
    LOGOUT:"Logged out successfully",
    DATABASE_ERROR:"Database error",
    INVALID_TOKEN:"Invalid token",
    RESET_TOKEN_SENT:"Password reset token sent",
    PASSWORD_RESET_SUCCESS:"Password reset successfully",
    PROFILE_UPDATED:"Profile updated successfully",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
    VERIFICATION_EMAIL_SENT: "Verification email sent",
    ALL_USERS:"All Users Records",
    EMAIL_VERIFIED: "Email verified successfully",
    ACCOUNT_DELETED: "Account deleted successfully",
    ACCOUNT_NOT_FOUND_OR_ACTIVE: "Account not found or already active",
    ACCOUNT_RECOVERED: "Account recovered successfully",
    TOKEN_MISSING:"Token messing"
};
